-- Create Categories Table
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  icon text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Products Table
create table public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  price numeric not null,
  original_price numeric,
  image_url text, -- changed from image to match typical pattern
  category text,
  description text,
  rating numeric default 0,
  is_amazing boolean default false,
  stock_count integer default 0,
  specifications jsonb, -- array of {label, value} objects
  variants jsonb, -- array of existing variant objects
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Posts (Reels) Table
create table public.posts (
  id bigint generated by default as identity primary key,
  video_url text not null,
  thumbnail text,
  caption text,
  likes integer default 0,
  product_ids jsonb, -- array of product IDs linked to this post
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Blogs Table
create table public.blogs (
  id bigint generated by default as identity primary key,
  title text not null,
  excerpt text,
  content text,
  cover_image text,
  author text,
  category text,
  read_time integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Orders Table (Simple version)
create table public.orders (
  id bigint generated by default as identity primary key,
  total_price numeric not null,
  status text default 'pending', -- pending, shipped, cancelled
  items jsonb, -- array of {productId, quantity}
  user_address text,
  user_phone text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Storage Bucket for Product Images
insert into storage.buckets (id, name, public) 
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

-- Create Storage Bucket for Reels/Videos
insert into storage.buckets (id, name, public) 
values ('reels', 'reels', true)
on conflict (id) do nothing;

-- Set up RLS (Row Level Security) - Allowing public read access for now
alter table public.categories enable row level security;
create policy "Public categories are viewable by everyone" on public.categories for select using (true);
create policy "Public categories are insertable by everyone" on public.categories for insert with check (true);

alter table public.products enable row level security;
create policy "Public products are viewable by everyone" on public.products for select using (true);
create policy "Public products are insertable by everyone" on public.products for insert with check (true);
create policy "Public products are updatable by everyone" on public.products for update using (true);
create policy "Public products are deletable by everyone" on public.products for delete using (true);

alter table public.posts enable row level security;
create policy "Public posts are viewable by everyone" on public.posts for select using (true);
create policy "Public posts are insertable by everyone" on public.posts for insert with check (true);
create policy "Public posts are deletable by everyone" on public.posts for delete using (true);

alter table public.blogs enable row level security;
create policy "Public blogs are viewable by everyone" on public.blogs for select using (true);

alter table public.orders enable row level security;
create policy "Public orders are viewable by everyone" on public.orders for select using (true);
create policy "Public orders are insertable by everyone" on public.orders for insert with check (true);

-- Storage Policies
create policy "Public Access" on storage.objects for select using ( bucket_id in ('product-images', 'reels') );
create policy "Public Insert" on storage.objects for insert with check ( bucket_id in ('product-images', 'reels') );
